kind: pipeline
name: default
type: kubernetes

volumes:
- name: m2
  host:
    path: /var/lib/cache

steps:
- name: mvn-auth
  image: robertstettner/drone-mvn-auth
  debug: true
  volumes:
  - name: m2
    path: ~/
  environment:
    REPO_USERNAME:
      from_secret: REPO_USERNAME
    REPO_PASSWORD:
      from_secret: REPO_PASSWORD
  servers:
    - id: github
      username: $REPO_USERNAME
      password: $REPO_PASSWORD
    - id: snapshot
      username: $REPO_USERNAME
      password: $REPO_PASSWORD
  profiles:
    - id: my-profile
      repositories:
        - id: github
          name: github repo
          url: https://github.com/iamvvra/spring-boot-distroless-jib/raw/mvn-repo/
          layout: default
  active_profiles:
      - my-profile  

- name: package
  image: gcr.io/cloud-builders/mvn
  volumes:
  - name: m2
    path: ~/
  commands:
    - mvn deploy -DskipTests=true
  when:
    branch:
      - master
    event:
      - push
  depends_on:
    # - test
    - mvn-auth
