kind: pipeline
name: default
type: docker

steps:
- name: test-and-build
  image: maven
  commands:
  - mvn clean test
  - mvn package -DskipTests=true

- name: build-docker-image
  image: maven
  commands:
  - mvn compile jib:build -Djib.allowInsecureRegistries=true
