kind: pipeline
name: default
type: kubernetes

steps:
- name: code-analysis
  image: gcr.io/cloud-builders/mvn
  environment:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  commands:
    - mvn sonar:sonar -Dsonar.projectKey=spring-boot-distroless-jib -Dsonar.host.url=$sonar_host -Dsonar.login=$sonar_token
- name: test
  image: gcr.io/cloud-builders/mvn
  commands:
  - mvn test
  depends_on:
    - code-analysis
  when:
    branch:
      - feature/*
      - master
    event:
      - pull_request
      - push
- name: build-image
  image: gcr.io/cloud-builders/mvn
  environment:
    USERNAME:
      from_secret: REGISTRY_USERNAME
    PASSWORD:
      from_secret: REGISTRY_PASSWORD
  commands:
    - echo "$USERNAME"
    - mvn package jib:build -DskipTests=true -Djib.allowInsecureRegistries=true -Djib.to.auth.username=$USERNAME -Djib.to.auth.password=$PASSWORD
  depends_on:
    - code-analysis
    - test
  when:
    branch:
      - master
    event:
      - push
