kind: pipeline
name: default
type: kubernetes

steps:
- name: test
  image: gcr.io/cloud-builders/mvn
  commands:
  - mvn test
  when:
    branch:
      - feature/*
      - master
    event:
      - pull_request
      - push
- name: mvn-auth
  image: robertstettner/drone-mvn-auth
  debug: true
  volumes:
  - name: m2
    path: ~/
  environment:
    REPO_USERNAME:
      from_secret: REPO_USERNAME
    REPO_PASSWORD:
      from_secret: REPO_PASSWORD
  servers:
    - id: github
      username: $REPO_USERNAME
      password: $REPO_PASSWORD
    - id: snapshot
      username: $REPO_USERNAME
      password: $REPO_PASSWORD
  profiles:
    - id: my-profile
      repositories:
        - id: github
          name: github repo
          url: https://github.com/iamvvra/spring-boot-distroless-jib/raw/mvn-repo/
          layout: default
  active_profiles:
      - my-profile  
- name: package
  image: gcr.io/cloud-builders/mvn
  volumes:
  - name: m2
    path: ~/
  commands:
    - mvn deploy -DskipTests=true
  when:
    branch:
      - master
    event:
      - push
  depends_on:
    - test
    - mvn-auth
- name: build-image
  image: gcr.io/cloud-builders/mvn
  environment:
    USERNAME:
      from_secret: REGISTRY_USERNAME
    PASSWORD:
      from_secret: REGISTRY_PASSWORD
  commands:
    - echo "$USERNAME"
    - mvn package jib:build -DskipTests=true -Djib.allowInsecureRegistries=true -Djib.to.auth.username=$USERNAME -Djib.to.auth.password=$PASSWORD
  depends_on:
    - test
  when:
    branch:
      - master
    event:
      - push