kind: pipeline
name: default
type: kubernetes

steps:
- name: test-build-image
  image: maven
  environment:
    USERNAME:
      from_secret: REGISTRY_USERNAME
    PASSWORD:
      from_secret: REGISTRY_PASSWORD
  commands:
  - mvn package jib:build -Djib.allowInsecureRegistries=true -Djib.to.auth.username=$USERNAME -Djib.to.auth.password=$PASSWORD
